---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "leader-election-service.fullname" . }}-sa
  labels:
    {{- include "leader-election-service.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "leader-election-service.fullname" . }}-role
  labels:
    {{- include "leader-election-service.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "leader-election-service.fullname" . }}-rolebinding
  labels:
    {{- include "leader-election-service.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "leader-election-service.fullname" . }}-sa
roleRef:
  kind: Role
  name: {{ include "leader-election-service.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
